### PR TITLE
Convert historical data to useful units

### PR DESCRIPTION
**Pull request by tatiana-boura**
This PR, if merged, closes Issue #44 .

It makes sure that the historical data that we acquired prior to November 2023 **when processed** are converted to the units the domain experts are more accustomed to. These units align with those used in the stored data after November 2023, such as kWatts in the solar radiation example.

The testcases have been updated accordingly.

(PS. In case you are wondering why it took me so long.. floating point precision is a pain!)

### CODE REVIEW

**Comment by stasinos** [comment]
PYRANOMETER values are now too small, max: 0.149, mean: 0.023, considering that only values above 0.15 are considered.
I suspect PYRANOMETER should be div_1000 not div_10000

PS I also do not understand why people won't chose units that would make it possible to work with ints, but such is life.

**Comment by tatiana-boura** [comment]
That is weird, in the live data we divide it by 10000 and the values seem to be as expected (cf. Grafana).
Let me check and brb.

**Comment by stasinos** [comment]
Quoting from GK:
"PYRANOMETER > +0.15 kW/m2 μονάδες σύμφωνα με ότι φαίνεται στο grafana"
I think it is best to clarify with them before putting more time into this.

**Comment by stasinos** [comment]
OUTDOOR TEMP is also off by a factor of 10. Remember August last year?

2023-08-31 18:37:45          2.91

**Comment by tatiana-boura** [comment]
Yes, I aggree. I have already contacted GM and awaiting response regarding, whether the hist results have been converted to _some_ unit, other than the PLC default.

**Comment by tatiana-boura** [comment]
GM responded and confirmed that all measurements are already converted in the historical data, except for the 'PYRANOMETER' which should be translated from $W/m^2$ to $kW/m^2$ by dividing with 1000, which makes your intuition correct @stasinos.

The commit 97dc07b does exactly that.

**Comment by stasinos** [comment]
Looks good now.

**Pull request merged**
