### PR TITLE
Weather data processing

### PR DESCRIPTION
**Pull request by nataliakoliou**
This PR introduces `weather.py`, a script designed to process HTML weather forecasting data into CSV format. The script parses HTML files stored in our database, extracting four (4) types of forecasting data:

1. Current (C): Real-time weather data for the current date.
2. Historical (H): Insights into past weather conditions for the month of the current date across multiple years.
3. Brief (B): Summary of weather conditions for the next 4 days.
4. Detailed (D): Comprehensive view of weather conditions for the week (7 days) with updates every 3 hours.

For example:
- **C-20240312.csv**: Real-time data for 12/03/2024.
- **H-20240312.csv**: Historical data aggregated from past years, 2016-2021, 2020-2021, etc., for March.
- **B-20240312.csv**: Brief summary of weather conditions for 12/03/2024-15/03/2024.
- **D-20240312.csv**: Detailed forecasts for 12/03/2024-18/03/2024, with updates every 3 hours (02:00, 05:00, 08:00, etc.).

This PR addresses the need to incorporate real-time weather data into our prediction models, partially resolving Issue #57.

### CODE REVIEW

**Comment by stasinos** [comment]
The dependency on the on-line translation service might break without notice and is also unnecessary simply for mapping month names. Please remove and replace with a static mapping from month names to month ordinals, or use a locale-aware date parser.

**Comment by tatiana-boura** [comment]
Besides the HTML weather data, this branch accounts for parsing and processing the format introduced by the ```openweathermap```.

**Comment by stasinos** [comment]
@tatiana-boura I do not see how the outputs from weather:main end up in the `data/obs_weather.txt` file read by classification_dataset:main

**Comment by stasinos** [comment]
I added a note in data/README.md, we will expand upon in with PLC data in the relevant branches after merging this here.

**Comment by stasinos** [comment]
The "rain" and "snow" series are also from OpenWeatherMap. It was a (not necessarily correct) design choice to place them in different timeseries, because they are sparse (only published by the API when relevant). Please add those as well.

**Pull request merged**
